### ISSUE TITLE
JSCoverage : Permission denied generating coverage report

### ISSUE THREAD

**Issue by vishalnit1389** [node-modules/jscover#14]
I am trying to generate a coverage report. I am running jscoverage from Makefile as following

make coverage
```
coverage: test
    @mv ./node_modules/kuler ./node_modules/kuler.actual
    @node_modules/jscoverage --no-highlight ./node_modules/sample.actual ./node_modules/sample
    @./node_modules/.bin/mocha --timeout 30s  -R html-cov test/unit > coverage.html
    @rm -rf ./node_modules/sample
    @mv ./node_modules/sample.actual ./node_modules/sample
```

```
test: dummy
    @node_modules/mocha/bin/mocha --timeout 100s test/db
    @node_modules/mocha/bin/mocha \
    --reporter spec \
    --ui bdd \
    --timeout 30s \
    test/unit \
    test/bug_test
```
I am getting permission denied make: node_modules/jscoverage: 
Permission denied make: *** [coverage] Error 1

Can someone please help?

**Comment by saper** [comment]
Isn't `node_modules/jscoverage` a directory? Your directory structure looks a bit strange.

Can you post the output of

`find .`

**Comment by vishalnit1389** [comment]
Thanks for the reply, 
node_modules/jscoverage is indeed a directory . Since the above code is in node.js , command node_modules/jscoverage runs  it's index file. 

Do you want to see the directory structure of whole project or just for jscoverage ?

**Comment by saper** [comment]
No, it won't work. You need to `node node_modules/jscoverage`. How can shell know this *directory* should be executed?

**Comment by vishalnit1389** [comment]
Sorry for the mistake . This time i executed jscoverage  by command ./node_modules/.bin/jscoverage
Now i am getting JS_Parse_Error

[/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, filename, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204:11)
    at parse_error (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:314:9)
    at Object.next_token [as input] (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:567:9)
    at next (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:666:25)
    at Object.parse (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:652:15)
    at Object.Instrument.process (/Users/visha/kulerapi/node_modules/jscoverage/lib/instrument.js:62:22)
    at Object.exports.process (/Users/visha/kulerapi/node_modules/jscoverage/lib/jscoverage.js:133:18)
    at Object.exports.processFile (/Users/visha/kulerapi/node_modules/jscoverage/index.js:206:18)
    at help (/Users/visha/kulerapi/node_modules/jscoverage/bin/jscoverage:65:20)](url)

**Comment by vishalnit1389** [comment]
Sorry for my mistake . This time i ran the jscoverage through ./node_modules/.bin/jscoverage but i am getting below mentioned error.

 /Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, filename, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/Users/visha/kulerapi/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204:11)
    at parse_error (/Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:314:9)
    at Object.next_token [as input] (/Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:567:9)
    at next (/Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:666:25)
    at Object.parse (/Users/visha/proj/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:652:15)
    at Object.Instrument.process (/Users/visha/proj/node_modules/jscoverage/lib/instrument.js:62:22)
    at Object.exports.process (/Users/visha/proj/node_modules/jscoverage/lib/jscoverage.js:133:18)
    at Object.exports.processFile (/Users/visha/proj/node_modules/jscoverage/index.js:206:18)
    at help (/Users/visha/proj/node_modules/jscoverage/bin/jscoverage:65:20)

**Comment by saper** [comment]
Die you check for syntax errors in your code?

I think the original issue is solved. Can we close this?
